# Проверять сообщения в чате
Chat:
  enable: true
  # Задержка перед отправкой сообщения в секундах
  delay: 1

# Проверять сообщения в командах
Command:
  enable: true
  # Всё что добавлено в чек команд, будет проверяться в черном листе, если черный лист false, то всё что в чек, не будет проверяться.
  black list: true
  check command:
    - m
    - msg
    - tell
    - me
    - r
  # Задержка перед отправкой сообщения в секундах
  delay: 3

block:
  # Проверка на повторяющиеся сообщения
  old msg: true
  # Проверка на заблокированные слова
  bad word: true
  # Проверка на кпс
  caps: true
  # Проверка на одинаковые символы в сообщении
  repeated text: true

# Автоматически заменит фразу "Oleg123, привет!" на "/m Oleg123 привет!"
auto private msg:
  enable: false
  # Разрешение, которое должно быть у игрока для выполнения команды, если пусто - разрешение игнорируется.
  has permission: ""

# Запрещенные слова, сообщения в чате будет видно только тому, кто его отправил.
# Поддержка регулярных выражений.
list word:
  - "fuck up!"
  - "\\.(mc|net|org)"

# Когда нарушений больше чем максимально возможных здесь наказаний, они очищаются.
violation:
  10:
    - "mute %player 30m"

# rchat.bypass - обход
# rchat.notify - получать уведомления о нарушениях
